CREATE TABLE IF NOT EXISTS `fn_users` (
  `userid` int(11) NOT NULL AUTO_INCREMENT,
  `password` varchar(128) NOT NULL,
  `uname` varchar(55) NOT NULL,
  `email` varchar(128) NOT NULL,
  `secondary_email` varchar(128) DEFAULT NULL,
  `activkey` varchar(128) NOT NULL DEFAULT '',
  `lastvisit` int(10) NOT NULL DEFAULT '0',
  `superuser` int(1) NOT NULL DEFAULT '0',
  `profile_image` varchar(750) DEFAULT NULL,
  `fname` varchar(100) DEFAULT NULL,
  `lname` varchar(100) DEFAULT NULL,
  `gender` int(11) DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `dob` date NOT NULL,
  `age` varchar(20) DEFAULT NULL,
  `mageid` int(11) NOT NULL,
  `socialnetwork` varchar(45) DEFAULT NULL,
  `socialnetworkid` varchar(150) DEFAULT NULL,
  `usertypeid` int(11) DEFAULT NULL COMMENT '63-Web 64-Mobile',
  `status` int(1) NOT NULL DEFAULT '0',
  `zipcode` int(11) NOT NULL,
  `createtime` datetime NOT NULL,
  `createdby` int(11) NOT NULL,
  `updatedby` int(11) DEFAULT NULL,
  `updatedate` datetime DEFAULT NULL,
  `trackid` int(50) DEFAULT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE KEY `email` (`email`),
  KEY `status` (`status`),
  KEY `superuser` (`superuser`),
  KEY `fk_user_gender` (`gender`),
  KEY `fk_user_type` (`usertypeid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1167 ;