<?php $this->layout = '/layouts/column1';?>
<?php echo "test";exit; ?>
<div class="main-container">
  <div class="finao-caption"><img src="images/finao-caption.png" /></div>
  <div class="content-block">
  	<div class="container">
			<section class="tabs">
	            <input id="tab-1" type="radio" name="radio-set" class="tab-selector-1" checked="checked" />
		        <label for="tab-1" class="tab-label-1">About Us</label>
		
	            <input id="tab-2" type="radio" name="radio-set" class="tab-selector-2" />
		        <label for="tab-2" class="tab-label-2">FAQ</label>
		
	            <input id="tab-3" type="radio" name="radio-set" class="tab-selector-3" />
		        <label for="tab-3" class="tab-label-3">FINAO Gives</label>
			
	            <input id="tab-4" type="radio" name="radio-set" class="tab-selector-4" />
		        <label for="tab-4" class="tab-label-4">Terms &amp; Conditions</label>
                
                <input id="tab-5" type="radio" name="radio-set" class="tab-selector-5" />
		        <label for="tab-5" class="tab-label-5">Group Purchase</label>
            
			    <div class="clear-shadow"></div>
				
		        <div class="content">
			        <div class="content-1" style="height:650px!important; overflow-y:scroll; overflow-x:hidden;">
						<h2>About Us</h2>
                        <p>About Us should really say, "About You", because YOU help define the culture of the FINAO&regNation. Here we live our vision: to foster a culture where it's fun and cool to live a goal-oriented life.</p>
                        <p>FINAO&reg;Nation was built for you as a place to declare your goals and assert what is important to you. More of a springboard than a platform. With FINAO you share aspirations that align with your passions and capabilities, not those of society. We call these statements of commitment FINAOs (fin-nāy-o). Failure Is Not An Option.</p>
                        <p>We know everyone operates differently, so we offer many unique and engaging ways for you to express your FINAO. These include sharing pictures or video through social media, an online community of supporters, a portfolio of who you are, a mobile phone app, and our innovative FlipWearTM line of casual apparel where you can wear your FINAO and reveal it if you wish. </p>
                        <p>Our website is the starting point for all of the FINAO elements you can use. Here, you create a simple profile and establish your FINAOs. Through your profile you can share your FINAOs with your supporters or keep your FINAOs confidential.</p>
                        <p>At FINAO&reg;Nation you have total control of your information and it remains private until you choose to share.   </p>
                        <p>&nbsp;</p>
                        
						<h2>History</h2>
						<p>The FINAO vision began in the early 1990's. While working on a major technology venture we faced numerous challenges and endured great personal expense. At one point we were prepared to abandon the project. After considering all the sacrifices we had made, we were determined not to quit and decided failure was not an option. In the end, the project was enormously successful. From that point, we were determined to establish our own definitions of success. We were convinced that when we defined goals and meaningful aspirations in our lives, Failure Is Not An Option.  We soon embodied FINAO and discovered we were not alone. We found hundreds of examples of people everywhere who were defining what was important, facing challenges and achieving success on their own terms.  We all became FINAO.</p>
                        <p>&nbsp;</p>
                        
                        <h2>Your FINAO&reg;Team</h2>
                        <p>Our team here at FINAO is a melting pot of stories, values, and passions. We are a mix of career minded individuals deciding it's time to put family first, risk takers leaving secure positions to follow dreams, and those waking up saying, "I will leave a positive mark on this world." FINAO exemplifies all of that.</p>
                        <p>We are laser focused on the personal pursuit of aspirations, commitments, values, and goals. We are all distinct individuals defining success on our own terms. Despite our unique personal values and definitions of success we are driven by one principle – Failure Is Not An Option.
That passion is evident in everything we do, but most importantly in manifests in our efforts to ensure our members have a great experience while expressing their own FINAO.</p>
                        
				    </div>
			        <div class="content-2">
						<h2>FAQ</h2>
				    </div>
			        <div class="content-3">
						<h2>Portfolio</h2>
                        <p>The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.</p>
						<h3>Examples</h3>
						<p>Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass. </p>
				    </div>
				    <div class="content-4" style="height:650px!important; overflow-y:scroll; overflow-x:hidden;">
						<h2>Terms &amp; Conditions</h2>
                        <p>By placing an order on this web site, you indicate that you have read and agree to the following Terms &amp; Conditions.</p>
                        <p><span class="orange">READ CAREFULLY</span>. This Terms of Use Agreement ("Terms of Use") applies to use of the FINAO&reg; website located at <a href="#" class="orange-link font-14px">FINAONation.com</a> (the "Site"). The Site is the property of FINAO (together with its affiliated companies). Before you make any purchases, you must first establish a customer account ("My Account"). BY CREATING AN ACCOUNT YOU AGREE TO THESE TERMS OF USE. IF YOU DO NOT AGREE, DO NOT CREATE AN ACCOUNT AND DO NOT USE THE SITE.</p>
                        <p>FINAO reserves the right, at its sole discretion, to change, add or remove portions of this Terms of Use, at any time. It is your responsibility to check this Terms of Use each time before using the Site. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes. You agree that all subsequent purchases by you will be subject to the terms and conditions of this Terms of Use, which shall apply until we post a modified Terms of Use and then in accordance with such modified Terms of Use. As long as you comply with this Terms of Use and any such modifications, FINAO grants you ("End User") a personal, non-exclusive, non-transferable, non-sub licensable, limited privilege to enter and use the Site.</p>
                        <p><span class="orange">Content, Copyright and Trademark Notice.</span> All media (downloaded or samples), software, text, images, graphics, user interfaces, music, videos, photographs, trademarks, logos, artwork and other content on the Site (collectively, "Content"), including but not limited to the design, selection, arrangement, and coordination of such Content on the Site is owned or licensed by or to FINAO, and is protected by copyright, trade dress, and trademark laws, and various other intellectual property rights laws. Except as expressly provided in this Terms of Use, no part of the Site and no Content may be reproduced, recorded, retransmitted, sold, rented, broadcast, distributed, published, uploaded, posted, publicly displayed, altered to make new works, performed, digitized, compiled, translated or transmitted in any way to any other computer, website or other medium or for any commercial purpose, without FINAO's prior express written consent. Except as expressly provided herein, you are not granted any rights or license to patents, copyrights, trade secrets, trade dress, rights of publicity or trademarks with respect to any of the Content, and FINAO  reserves all rights not expressly granted hereunder. FINAO expressly disclaims all responsibility and liability for uses by you of any Content obtained on or in connection with the Site.</p>
                        <p>FINAO&reg; and FlipWear&reg; are registered trademarks, trademarks or service marks of JoMoWaG, LLC – Dba FINAO. All custom graphics, icons, logos and service names are registered trademarks, trademarks or service marks of JoMoWaG, LLC – Dba FINAO. All other trademarks or service marks are property of their respective owners. The use of any FINAO trademark or service mark without FINAO's express written consent is strictly prohibited.</p>
                        <p>By submitting a design to FINAO, or using logos stored on the site, you warrant and represent that you are the sole, legal owner or licensee of all rights, including copyright, to each copyright, trademark, service mark, trade name, logo, statement, portrait, graphic, artwork, photograph, picture or illustration of any person or any other intellectual property included in such design.</p>
                        <p>Further you warrant and represent that no part of the design: (a) violates or infringes upon any common law or statutory right of any person or entity, including, but not limited to, rights relating to copyrights, trademarks, contract rights, moral rights or rights of public performance; (b) is the subject of any notice of such infringement you have received; or (c) is subject to any restriction or right of any kind or nature whatsoever which would prevent FINAO  from legally reproducing the images or text submitted.</p>
                        <p>You agree to defend, at your sole expense, any claim, suit, or proceeding brought against FINAO which relates to, or is based upon, a claim that any portion of the design infringes or constitutes wrongful use of any copyright, trademark, or other right of any third party, provided that FINAO gives you written notice of any such claim and provides you such reasonable cooperation and assistance as you may require in the defense thereof. You shall pay any damages and costs assessed against FINAO pursuant to such a suit or proceeding. Further, you agree to indemnify and hold FINAO  harmless from and with respect to any such loss or damage (including, but not limited to, reasonable attorneys' fees and costs) associated with any such claim, suit or proceeding.</p>
                        <p>All items shown on this web site containing corporate logos or registered trademarks are shown only to illustrate FINAO's logo reproduction capabilities. Purchase of merchandise from FINAO in no way, shape or form grants you permission to reproduce logos, nor does it transfer, grant or lease ownership of any logos or trademarks to you.</p>
                        
                        <p><span class="orange">Registration; Customer Accounts; Use of Site.</span> Certain services offered on or through the Site require you to first open an Account. You are responsible for maintaining the confidentiality of your Account information, including your password, and for all activity that occurs under your account. You agree to notify FINAO immediately of any unauthorized use of your account or password, or any other breach of security. You may be held liable for losses incurred by FINAO or any other user of the Site due to someone else using your password or customer account. You may not use anyone else's password or customer account at any time. You may not attempt to gain unauthorized access to the Site. Should you attempt to do so, assist others in making such attempts, or distributing instructions, software or tools for that purpose, then your customer Account will be terminated. You agree to provide us with accurate, current and complete information about yourself and your billing information as prompted by the registration process. You may update any of your Account information, designate a different credit card to be billed, or change the applicable expiration date on your currently designated credit card, by clicking on the My Account button and selecting the appropriate link. You may not use any automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy, probe, test or monitor any portion of the Site or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Site or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Site. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Site or any of the systems or networks comprising or connected to the Site.</p>
                        <p>You also agree that FINAO  may, in its sole discretion and without prior notice to you, terminate your access to the Site and your Account for any reason, including without limitation: (1) attempts to gain unauthorized access to the Site or assistance to others' attempting to do so, (2) overcoming software security features limiting use of or protecting any Content, (3) discontinuance or material modification of the Site or any service offered on or through the Site, (4) violations of this Terms of Use, (5) failure to pay for purchases, (6) suspected or actual copyright infringement, (7) unexpected operational difficulties, or (8) requests by law enforcement or other government agencies. You agree that FINAO will not be liable to you or to any third party for termination of your access to the Site.</p>
                        
                        <p><span class="orange">Consent To Collection, Use & Disclosure of Your Personal Information.</span> As more fully described in our Privacy Policy, you must disclose certain Personally Identifiable Information to use our Site, register, and make purchases. As a condition of registering with our Site or making any purchases of any products and/or services or conduct any transactions, you represent that you have first read our Privacy Policy and consent to the collection, use and disclosure of your Personally Identifiable Information and Non-Personally Identifiable Information as described in our Privacy Policy. Our Privacy Policy's terms and conditions will change from time to time, and as a condition of browsing the Site, using any features or making any purchase, you agree that you will first review our Privacy Policy prior to making any initial or subsequent purchases.</p>
                        
                        <p>While FINAO takes reasonable steps to safeguard and to prevent unauthorized access to your personal information, we cannot be responsible for the acts of those who gain unauthorized access, and we make no warranty, express, implied, or otherwise, that we will prevent unauthorized access to your private information. IN NO EVENT SHALL FINAO OR ITS AFFILIATES BE LIABLE FOR ANY DAMAGES (WHETHER CONSEQUENTIAL, DIRECT, INCIDENTAL, INDIRECT, PUNITIVE, SPECIAL OR OTHERWISE) ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, A THIRD PARTY'S UNAUTHORIZED ACCESS TO YOUR PERSONAL INFORMATION, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, STRICT LIABILITY, TORT OR OTHER THEORIES OF LIABILITY, AND ALSO REGARDLESS OF WHETHER FINAO WAS GIVEN ACTUAL OR CONSTRUCTIVE NOTICE THAT DAMAGES WERE POSSIBLE.</p>
                        
                        <p><span class="orange">Consent To Our Communication With You By E-Mail.</span> By establishing an Account with us, and each time you make a purchase through our Site, you grant permission for FINAO to contact you at your e-mail address. To stop receiving our marketing emails, send an e-mail to us at <a href="#" class="orange-link font-14px">askus@finaonation.com</a> or follow the opt-out procedures set forth in such marketing emails. FINAO cannot be held responsible for emails not received due to SPAM filters installed by your Internet Service Provider (ISP), email provider or by you, the Customer. FINAO cannot be held responsible for order delays or failure to receive out of stock or declined notifications created by SPAM filters or other related computer software and/or hardware.</p>
                        
                        <p><span class="orange">Conditions of Sale and Payment Terms.</span> To purchase any goods and/or services on our Site, you must (a) be at least eighteen (18) years of age or the applicable state age of majority. Prior to the purchase of any goods or services on our Site, you must provide us with a valid credit card number and associated payment information including all of the following: (i) your name as it appears on the card, (ii) your credit card number, (iii) the credit card type, (iv) the date of expiration and (v) any activation numbers or codes needed to charge your card. By submitting that information to us, you hereby agree that you authorize us to charge your card at our convenience but within thirty (30) days of credit card authorization.</p>
                        <p><span class="orange">Methods of Payment, Credit Card Terms and Taxes.</span> All payments must be made by VISA, MasterCard, American Express, or Discover Card. Your card issuer agreement governs your use of your designated card, and you must refer to that agreement and not this Terms of Use to determine your rights and liabilities as a cardholder. YOU, AND NOT FINAO, ARE RESPONSIBLE FOR PAYING ANY UNAUTHORIZED AMOUNTS BILLED TO YOUR CREDIT CARD BY A THIRD PARTY. You agree to pay all fees and charges incurred in connection with your purchases (including any applicable taxes) at the rates in effect when the charges were incurred. Unless you notify FINAO  of any discrepancies within sixty (60) days after they first appear on your credit card statement, you agree that they will be deemed accepted by you for all purposes. If FINAO does not receive payment from your credit card issuer or its agent, you agree to pay all amounts due upon demand by FINAO or its agents. You are responsible for paying any governmental taxes imposed on your purchases and shipping, including, but not limited to, sales, use or value-added taxes. FINAO shall automatically charge and withhold the applicable sales tax for orders to be delivered to addresses within Washington State and any other states or localities that it deems are required.</p>
                        <p><span class="orange">Improper/Fraudulent Chargeback fee: $25.00. </span>
Explanation: Customers issuing chargeback(s) with their Credit Card's issuing Bank without proper cause will be billed any fees incurred by FINAO in disputing the chargeback as well as a $25.00 Chargeback fee. This is necessary to recover the charges we were billed by Visa/MasterCard/Discover Card when the no cause chargeback was issued. With this type of fraud/negligence on the rise, and little recourse given to the Merchant by the credit card issuers, we must protect ourselves from this new type of crime/negligence.</p>
				
                		<p><span class="orange">Order Acceptance Policy.</span> Your receipt of an electronic or other form of order confirmation does not signify our acceptance of your order, nor does it constitute confirmation of our offer to sell. FINAO reserves the right at any time after receipt of your order to accept or decline your order for any reason. FINAO further reserves the right any time after receipt of your order, without prior notice to you, to supply less than the quantity you ordered of any item. Your order will be deemed accepted by FINAO upon our shipment of products or delivery of services that you have ordered. All orders placed over $1000.00 (U.S.) must obtain pre-approval with an acceptable method of payment, as established by our credit and fraud avoidance department. We may require additional verifications or information before accepting any order.</p>
                        
                        
				    </div>
                    <div class="content-5">
						<h2>Contact</h2>
                        <p>You see? It's curious. Ted did figure it out - time travel. And when we get back, we gonna tell everyone. How it's possible, how it's done, what the dangers are. But then why fifty years in the future when the spacecraft encounters a black hole does the computer call it an 'unknown entry event'? Why don't they know? If they don't know, that means we never told anyone. And if we never told anyone it means we never made it back. Hence we die down here. Just as a matter of deductive logic.</p>
						<h3>Get in touch</h3>
						<p>Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing. </p>
				    </div>
		        </div>
			</section>
        </div>
  </div>
</div>