<?php
/* if(isset(Yii::app()->session['sesInvitedEmail']['invitedEmail'])){*/?>
<div class="middle-content">
<h1 class="page-headline">Terms & Conditions</h1>
<p class="blue-font15">General Terms and Conditions</p>
  <p class="run-text font-12px">Welcome to the internet web site <a class="blue-link" target="_blank" href="<?php echo Yii::app()->baseUrl;?>/index.php">www.parentvalet.com</a> (the “Site”), owned and operated by Parent Valet Inc., a Delaware corporation.  These Terms of Use (these “Terms”) govern your access to and use of the services, applications and websites (collectively, the “Services”) provided by Parent Valet Inc.  Please read these Terms carefully, as they constitute a binding agreement between you and Parent Valet Inc.  By accessing and/or using this Site and/or the Services, you agree to be bound by all of the terms and conditions described herein.  If you do not agree to all of these terms and conditions, you must not use the Site or the Services.  In these terms, the use of the words “Parent Valet”, “we”, “our” and “us” refer to Parent Valet Inc.  The words “user”, “you” and “your” refer to individuals who create profiles and/or use the Site or the Services.  If you are a minor, your parent or legal guardian must review and discuss these terms with you before you use the Site or the Services. </p> 
  <p class="run-text font-12px">The Site and the Services require users to register certain information with us, other users, and other third parties connected to us.   The following provisions are designed to generally explain what we expect of users, and what users can expect of us.  We appreciate your use of the Site and the Services, and hope that they are useful to you.</p>
  <p class="run-text font-12px">These Terms apply to your access and use of the Site and any mobile applications developed by Parent Valet on all platforms for which one exists.  These Terms do not alter in any way the terms or conditions of any other agreement you may have with us. If you are using the Services on behalf of any entity, you represent and warrant that you are authorized to accept these Terms on such entity’s behalf.   </p>
  <p class="run-text font-12px">We reserve the right to change or modify these Terms or any policy or guideline of the Site and/or the Services we offer at any time.  If we make any material changes in the way we collect, use, and/or share your personal information, we will notify you by sending an email to the email address you most recently provided us in your account, profile or registration (unless you have not provided an email address), and/or by prominently posting notice of the changes on the Site. Your use of the Site and the Services will be subject to the most current version of these Terms posted on the Site at the time of your use.  We recommend that you check the Site from time to time to inform yourself of any changes in these Terms or any of our other policies.  </p> 
  <p class="blue-font15" >Privacy Policy</p>
  <p class="run-text font-12px">Please refer to our <a class="blue-link" href="<?php echo Yii::app()->baseUrl;?>/index.php/site/page?view=privacy">Privacy Policy</a> for information on how we collect, use and disclose personally identifiable information we collect from our users. </p>
  <p class="blue-font15">Trademark and Materials</p>
  <p class="run-text font-12px">Our designs, text, graphics, pictures, information, data, software (and the selection and arrangement thereof) logos, code, and designs (collectively, the “Site Materials”) are all property of Parent Valet and are protected by intellectual property law.  Use of these items is subject to these Terms and is only permitted within normal use of the Site and the Service.  Your use of the Site and/or Service does not grant you any right or license to reproduce or otherwise use any Parent Valet or third-party trademarks or other Site Materials without our express written consent.</p>
  <p class="blue-font15">Your Rights and Responsibilities</p>
  <p class="blue-font15">Registration Data</p>
  <p class="run-text font-12px">As part of the Services we provide, you are able to register for an account (“Account”).  By registering for an Account, you agree to: (i) provide accurate, current and complete information about you as may be prompted by any signup, login and/or registration forms within our registration process (“Registration Data”); (ii) maintain the security of your password and identification; (iii) maintain and promptly update the Registration Data, and any other information you provide to us, to keep it accurate, current and complete; and (iv) accept all risks of unauthorized access to the Registration Data and any other information you provide to us.  Account registration is available only to individual, natural persons who are 18 years of age or older.  By registering for an Account, you acknowledge and agree that you are solely responsible for providing your own Internet or wireless access, and for any telecommunication charges or other charges that you incur through access and use of the Services, including without limitation any premium charges and surcharges due to bandwidth consumption, and any taxes payable by you in connection with such access and use.</p>
  <p class="blue-font15">Limited License</p>
  <p class="run-text font-12px">You may use the Services only in compliance with these Terms and all applicable local, state, national, and international law, rules, and regulations.</p>
  <p class="run-text font-12px">You are granted a limited, non-sub-licensable license to access the Site and use the Services, and electronically copy, (except where prohibited without a license) and print to hard copy portions of the Site Materials (except third party content) for your informational, non-commercial and personal use only. The license is subject to these Terms and does not include: (i) any resale or commercial use of the Site or Services or the Site Materials therein; (ii) the distribution, public performance or public display of any Site Materials; (iii) modifying or otherwise making any derivative uses of the Site, the Services, or the Site Materials (or any portion thereof); (iv) use of any data mining, robots or similar data gathering or extraction methods; or (v) any use of the Site, the Services, or the Site Materials other than for their intended purpose. </p>
   <p class="run-text font-12px">Any use of the Site, the Services or the Site Materials other than as specifically authorized in these Terms, without our prior written permission, is strictly prohibited and will terminate the license granted in these Terms. Such unauthorized use may also violate applicable laws including, but not limited to, copyright and trademark laws and applicable communications regulations and statutes.  We have the right to terminate the Accounts of users who we believe in good faith to be violating any laws whatsoever.  Unless explicitly stated herein, nothing in these terms will be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time.</p>
   <p class="blue-font15">User Content</p>
   <p class="run-text font-12px">The Site allows users to create, upload, and share information in connection with the Services.  The Site allows you or other users to post, link, store, or otherwise make available a wide variety of information, text and/or other materials to others (“User Content”). You are solely responsible for your use of User Content and use it at your own risk. By posting any User Content, you represent and warrant that you have the lawful right to distribute and reproduce your User Content.  By using any User Content, you agree not to post, upload to, transmit, distribute, store, create or otherwise publish through our service any of the following:</p>
   <ul class="privacy-policy-bullets">
   <li>User Content that is unlawful, libelous, defamatory, obscene, pornographic, harassing, threatening, invasive of privacy or publicity rights, deceptive, fraudulent or otherwise objectionable (as determined in our reasonable discretion), including, without limitation, the names or any other personally identifiable information of students, teachers, administrators, staff persons or other school employees;</li>
   <li>User Content that would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party or that would any local, state, national or international law; </li>
   <li>User Content that may infringe any patent, trademark, trade secret, copyright or other intellectual or proprietary right of any party;</li>
   <li>User Content that impersonates any person or entity or otherwise misrepresents your affiliation with a person or entity; or that provides private information of any third party including addresses, phone numbers, email addresses, Social Security numbers and similar information; </li>
   <li>User Content that, in our sole judgment, is objectionable or which restricts or inhibits any other person from using and benefiting from our Services, including, without limitation, User Content that contains or installs any viruses, worms, malware, Trojan horses, or other harmful or destructive content;</li>
   <li>User Content that is spam, is machine- or randomly-generated, or contains unethical or unwanted commercial content, or that furthers unlawful acts (such as phishing) or misleads recipients as to the source of the material (such as spoofing);</li>
   <li>User Content that does not comply strictly with any carrier agreements and terms associated with your mobile device; and</li>
   <li>User content that attempts to disrupt the Site or the Services.</li>
   </ul>
   <p class="blue-font15">Fees and Payment</p>
   <p class="run-text font-12px">We may, now or in the future, charge a fee for certain service offerings and/or access levels.  When you purchase a service that has a fee, you have an opportunity to review and accept the fees that you will be charged, which we may change at any time and from time to time.  We may choose to temporarily change the fees for services for promotional events or new services, and such changes are effective when such temporary promotional events or new services are posted on the Site.  All fees are non-refundable, and under no circumstances will you be entitled to receive a refund or credit of any amounts paid to us. </p>
   <p class="blue-font15">Our Rights and Responsibilities</p>
   <p class="blue-font15">General</p>
   <p class="run-text font-12px">We take no responsibility and assume no liability for any User Content posted, stored or uploaded by you or any third party, or for any loss or damage thereto, nor are we liable for any mistakes, defamation, slander, libel, omissions, falsehoods, obscenity, pornography or profanity you may encounter.</p>
   <p class="run-text font-12px">As a provider of interactive services, we are not liable for any statements, representations, User Content or Advertiser and Corporate Partner Content (as defined below) provided by users in any form whatsoever on any area of the Site.  Although we have no obligation to screen, edit or monitor any of the User Content or Advertiser and Corporate Partner Content posted anywhere on the Site or made available through the Services, we reserve the right, and have absolute discretion, to remove, screen or edit any User Content and Advertiser and Corporate Partner Content posted or stored on the Site or made available through the Services at any time and for any reason without notice.  You are solely responsible for creating backup copies of and replacing any User Content you post or store on the Site, at your sole cost and expense.</p>
   <p class="run-text font-12px">We do not own the User Content you post on or otherwise submit to the Site, but in posting and/or otherwise submitting User Content to the Site, you grant us an irrevocable, worldwide, transferable, nonexclusive, royalty-free, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such User Content on or in any and all media (now known or hereafter developed).  You also hereby grant each user of the Site a non-exclusive license to access your User Content through the Site, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Content as permitted through the functionality of the Site and under these Terms. </p>
   <p class="run-text font-12px">The Services that we provide are always evolving and the form and nature of the Services that we provide may change from time to time without prior notice to you.  In addition, we may stop (permanently or temporarily) providing the Services (or any features within the Services) to you or to users generally and may not be able to provide you with prior notice.  We also retain the right to create limits on use and storage of User Content at our sole discretion at any time without prior notice to you.</p>
   <p class="blue-font15">Termination</p>
   <p class="run-text font-12px">We have the right, without notice and in our sole discretion, to terminate your license to use the Site and/or the Services, to terminate your Account and to block or prevent your future access to and use of the Site and/or the Services.</p>
   <p class="blue-font15">Advertisements and Promotions</p>
   <p class="run-text font-12px">We allow advertisers and corporate partners to post content on the Site and within the Services and provide links to sites and content of third parties (collectively the “Advertiser and Corporate Partner Content”) as a service to those interested in this information.  These advertisements may be targeted to users based on information they provide through use of the Site or the Services, queries made through the Services, or other information.  We do not control, endorse or adopt any Advertiser and Corporate Partner Content and we make no representation or warranties of any kind regarding the Advertiser and Corporate Partner Content.  The types and extent of advertising on the Site or in connection with the Services are subject to change.</p>
    <p class="blue-font15">Indemnification</p>
     <p class="run-text font-12px">You agree, at your sole expense, to defend, indemnify and hold us, our independent contractors, service providers and consultants, and their respective directors, employees and agents, harmless from and against any and all actual or threatened suits, actions, legal proceedings, judgments, and any other legal claims, damage awards, or other compulsory payment or performance of any kind arising out of, resulting from, attributable to or in any way incidental to: (i) your use of the Site, the Site Materials, and/or the Services; (ii) your conduct; (iii) your violation of these Terms or your violation of the rights of any third party; or (iv) any User Content posted by you.</p>
	  <p class="blue-font15">Disclaimer</p>
	  <p class="run-text font-12px">THE SITE, THE SERVICES, AND ALL SUBMISSIONS AND OTHER MATERIALS, INFORMATION, PRODUCTS AND SERVICES INCLUDED IN OR MADE AVAILABLE IN CONNECTION WITH THE SITE AND THE SERVICES ARE PROVIDED “AS IS,” WITH NO WARRANTIES WHATSOEVER. PARENT VALET AND ITS LICENSORS EXPRESSLY DISCLAIM TO THE FULLEST EXTENT PERMITTED BY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS. PARENT VALET AND ITS LICENSORS DISCLAIM ANY WARRANTIES REGARDING THE ACCURACY, SECURITY, RELIABILITY, TIMELINESS, AVAILABILITY, COMPATIBILITY AND PERFORMANCE OF THE SITE AND THE SERVICES. PARENT VALET AND ITS LICENSORS DISCLAIM ANY WARRANTIES FOR ANY INFORMATION OR ADVICE OBTAINED THROUGH THE SITE, THE SERVICE OR ANY SUBMISSION OR ANY PARENT VALET SERVICE. PARENT VALET AND ITS LICENSORS DISCLAIM ANY WARRANTIES FOR SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON THE SITE OR IN CONNECTION WITH ANY PARENT VALET SERVICES OR RECEIVED THROUGH ANY LINKS PROVIDED BY THE SITE OR THE SERVICES, AS WELL AS FOR ANY INFORMATION OR ADVICE RECEIVED THROUGH ANY LINKS PROVIDED IN ON THE SITE OR THROUGH THE SERVICES</p>

<p class="run-text font-12px">YOU AGREE THAT YOUR USE OF THE SITE AND ALL SUBMISSIONS SHALL BE AT YOUR SOLE RISK.</p>

<p class="run-text font-12px">YOU UNDERSTAND AND AGREE THAT YOU DOWNLOAD OR OTHERWISE OBTAIN MATERIAL OR DATA THROUGH THE USE OF THE SITE OR THE SERVICES, INCLUDING BUT NOT LIMITED TO ANY SUBMISSION(S), AT YOUR OWN DISCRETION AND RISK. WE DO NOT WARRANT THAT ANY CONTENT OR SUBMISSIONS WILL BE ERROR-FREE, THAT ACCESS THERETO WILL BE UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT DATA WILL NOT BE LOST OR THAT THE SITE OR THE SERVER THAT MAKES SUCH CONTENT AVAILABLE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.  IN SUCH EVENT, YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.  WE DO NOT WARRANT OR MAKE ANY REPRESENTATION REGARDING THE USE OR THE RESULTS OF THE USE OF ANY CONTENT.  YOU HEREBY IRREVOCABLY WAIVE ANY CLAIM AGAINST PARENT VALET, ITS AFFILIATES, SHAREHOLDERS, DIRECTORS, OFFICERS, EMPLOYEES AND AGENTS WITH RESPECT TO THE SITE, THE SERVICES AND CONTENT AND ANY CONTENT YOU PROVIDE TO THIRD PARTIES (INCLUDING CREDIT CARD AND OTHER PERSONAL INFORMATION). 
</p>
	  <p class="blue-font15">Limitation of Liability</p>
	  <p class="run-text font-12px">PARENT VALET, ITS OFFICERS, DIRECTORS, EMPLOYEES, AFFILIATES AND AGENTS ASSUME NO LIABILITY OR RESPONSIBILITY FOR, AND IN NO EVENT, INCLUDING NEGLIGENCE, SHALL PARENT VALET, ITS OFFICERS, DIRECTORS, EMPLOYEES, AFFILIATES OR AGENTS, BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM, ANY:</p>
	  <ul class="privacy-policy-bullets">
	  <li>PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITE;</li>
	  <li>ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN;</li>
	  <li>ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SITE OR THE SERVICES;</li>
	  <li>ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITE OR THE SERVICES, OR SITES LINKED TO BY THE SITE, BY ANY THIRD PARTY; AND/OR</li>
	  <li>ANY ERRORS OR OMISSIONS IN ANY SUBMISSION(S) OR OTHER CONTENT MADE AVAILABLE BY PARENT VALET, OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY SUBMISSION(S) OR OTHER CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SITE OR THE SERVICES, </li>
	  </ul>
	  <p class="run-text font-12px">IN ALL CASES WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT PARENT VALET IS OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION. IN ANY EVENT, PARENT VALET’S AGGREGATE LIABILITY SHALL NOT EXCEED $1000.00.</p>
	  	  <p class="blue-font15">Repeat Infringer Policy</p>
		  <p class="run-text font-12px">In accordance with the Digital Millennium Copyright Act (“DMCA”) and other applicable laws, we have adopted a policy of terminating, in appropriate circumstances and at our sole discretion, subscribers or account holders who are deemed to be repeat infringers. We may also at our sole discretion limit access to our service and/or terminate the accounts of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement. Additionally, we reserve the right to limit access to our service and/or terminate accounts of any users for reasons of our own discretion, that we are not obligated to reveal, at any time.</p>
		   <p class="blue-font15">Copyright Complaints</p>
		   <p class="run-text font-12px">If you believe that anything on the Site or in the Services infringes upon any copyright which you own or control you may file a notification of such infringement with our Designated Agent as set forth below.</p>

<p class="run-text font-12px">E-Mail Address of Designated Agent: <a href="mailto:customersupport@parentvalet.com" class="blue-link">
customersupport@parentvalet.com.</a></p>

<p class="run-text font-12px">Please see 17 U.S.C. § 512(c)(3) for the requirements of a proper notification. You should note that if you knowingly misrepresent in your notification that the material or activity is infringing, you will be liable for any damages including, but not limited to, costs and attorneys’ fees, incurred by us or the alleged infringer as the result of our relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing.
</p>
		    <p class="blue-font15">Questions & Contact Information</p>
			<p class="run-text font-12px">Questions, comments and any other correspondence regarding the Site or the Services may be directed to us at the email address <a href="mailto:customersupport@parentvalet.com" class="blue-link">customersupport@parentvalet.com.</a> </p>
			<p class="blue-font15">Last Updated: December 10, 2012</p>
</div>
<?/*}else{
	$this->redirect(array('/'));
}*/?>