UPDATE `finaonation`.`fn_tilesinfo` SET `tilesinfo_id`='27', `tile_id`='27', `tilename`='Education', `tile_imageurl`='education.png', `status`='1', `createdby`='0', `updatedby`='0' WHERE `tilesinfo_id`='50';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='51';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='70';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='1';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='6';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='8';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='15';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='19';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='23';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='25';
UPDATE `finaonation`.`fn_tilesinfo` SET `status`='0' WHERE `tilesinfo_id`='26';
